### ISSUE TITLE
Unable to run docker compose run

### ISSUE THREAD

**Issue by ronnzw** [terrameijar/invoices#15]
`docker compose run` is not running after the build, it requires another argument.

![Screenshot 2023-09-12 at 19 02 07](https://github.com/terrameijar/invoices/assets/17087071/1f3b66ab-cb57-49bd-b3c0-193deabd44d8)

**Comment by terrameijar** [comment]
This isn't documented well but this project uses two containers; a web and nginx container. The web container runs django and gunicorn and the nginx container serves static files.

`docker compose run` is missing an argument. You use it to specify which container you want to run. So if you only want to run the web container you do `docker compose run web` or if you only want to run the nginx container you do `docker compose run nginx`.

It is easier to simply do `docker compose up` to run the entire project. @ronnzw would you like to update the README to show the correct command to run?

**Comment by ronnzw** [comment]
Yes, I'm happy to do that.
